"""Batch mix / process milestone types (pure domain)."""

from __future__ import annotations

# Weigh-tab / auto
MILESTONE_DRY_MIXING_STARTED = "dry_mixing_started"
MILESTONE_WATER_ADDED = "water_added"
MILESTONE_DRY_WET_MIX_STARTED = "dry_wet_mix_started"
MILESTONE_SETTLING_STARTED = "settling_started"
MILESTONE_FIELD_CAPACITY_REACHED = "field_capacity_reached"

# Batches tab
MILESTONE_COMPLETELY_MIXED = "completely_mixed"
MILESTONE_CONTAINERS_SEPARATED = "containers_separated"
MILESTONE_HEAT_TREATED = "heat_treated"
MILESTONE_STORED_FOR_COOLING = "stored_for_cooling"
MILESTONE_PRODUCTION_CYCLE_STARTED = "production_cycle_started"
MILESTONE_BATCH_COMPLETED = "batch_completed"
MILESTONE_BATCH_CREATED = "batch_created"

# Production inoculate / grow (schema v6)
MILESTONE_INOCULATED = "inoculated"
MILESTONE_MOVED_TO_INCUBATION = "moved_to_incubation"
MILESTONE_MOVED_TO_FRUITING = "moved_to_fruiting"
MILESTONE_HARVEST_STARTED = "harvest_started"
MILESTONE_HARVEST_RECORDED = "harvest_recorded"
MILESTONE_BATCH_NOTE = "batch_note"
MILESTONE_CHECK_REMINDER_SET = "check_reminder_set"

HEAT_STERILIZED = "sterilized"
HEAT_PASTEURIZED = "pasteurized"
HEAT_METHODS = frozenset({HEAT_STERILIZED, HEAT_PASTEURIZED})

WEIGH_MILESTONES = frozenset(
    {
        MILESTONE_WATER_ADDED,
        MILESTONE_DRY_WET_MIX_STARTED,
        MILESTONE_SETTLING_STARTED,
        MILESTONE_FIELD_CAPACITY_REACHED,
    }
)

BATCH_TAB_MILESTONES = frozenset(
    {
        MILESTONE_COMPLETELY_MIXED,
        MILESTONE_CONTAINERS_SEPARATED,
        MILESTONE_HEAT_TREATED,
        MILESTONE_STORED_FOR_COOLING,
        MILESTONE_PRODUCTION_CYCLE_STARTED,
    }
)

BATCH_STATUS_ACTIVE = "active"
BATCH_STATUS_COMPLETE = "complete"

# Master-batch lifecycle phases (category for dashboards + future FKs).
PHASE_PLANNED = "planned"
PHASE_DRY_MIXING = "dry_mixing"
PHASE_WET_MIXING = "wet_mixing"
PHASE_SETTLING = "settling"
PHASE_FIELD_CAPACITY = "field_capacity"
PHASE_MIXED = "mixed"
PHASE_SEPARATED = "separated"
PHASE_HEAT_TREATED = "heat_treated"
PHASE_COOLING = "cooling"
PHASE_IN_PRODUCTION = "in_production"
PHASE_INOCULATED = "inoculated"
PHASE_INCUBATING = "incubating"
PHASE_FRUITING = "fruiting"
PHASE_HARVESTING = "harvesting"
PHASE_COMPLETE = "complete"

MILESTONE_TO_PHASE: dict[str, str] = {
    MILESTONE_BATCH_CREATED: PHASE_PLANNED,
    MILESTONE_DRY_MIXING_STARTED: PHASE_DRY_MIXING,
    MILESTONE_WATER_ADDED: PHASE_WET_MIXING,
    MILESTONE_DRY_WET_MIX_STARTED: PHASE_WET_MIXING,
    MILESTONE_SETTLING_STARTED: PHASE_SETTLING,
    MILESTONE_FIELD_CAPACITY_REACHED: PHASE_FIELD_CAPACITY,
    MILESTONE_COMPLETELY_MIXED: PHASE_MIXED,
    MILESTONE_CONTAINERS_SEPARATED: PHASE_SEPARATED,
    MILESTONE_HEAT_TREATED: PHASE_HEAT_TREATED,
    MILESTONE_STORED_FOR_COOLING: PHASE_COOLING,
    # Legacy stub → keep mapping for older milestones
    MILESTONE_PRODUCTION_CYCLE_STARTED: PHASE_IN_PRODUCTION,
    MILESTONE_INOCULATED: PHASE_INOCULATED,
    MILESTONE_MOVED_TO_INCUBATION: PHASE_INCUBATING,
    MILESTONE_MOVED_TO_FRUITING: PHASE_FRUITING,
    MILESTONE_HARVEST_STARTED: PHASE_HARVESTING,
    MILESTONE_BATCH_COMPLETED: PHASE_COMPLETE,
}

DEFAULT_RECIPE_KEY = "wood_lover"
